DROP TABLE METADATA.ENROLLMENT;

DROP TABLE METADATA.STUDENTS;

DROP TABLE METADATA.COURSES;

CREATE TABLE METADATA.COURSES (
  ID                INTEGER     NOT NULL AUTO_INCREMENT,
  CODE              VARCHAR(10) NOT NULL,
  TITLE 	        VARCHAR(50)	NOT NULL,
  DESCRIPTION       VARCHAR(50)	NOT NULL,
  CREDITS           INTEGER     NOT NULL,
  PRIMARY KEY (ID));

CREATE TABLE METADATA.STUDENTS (
  ID                INTEGER   	NOT NULL AUTO_INCREMENT,
  FIRST_NAME 	    VARCHAR(50)	NOT NULL,
  LAST_NAME 	    VARCHAR(50)	NOT NULL,
  EMAIL             VARCHAR(50)	NOT NULL,
  MAJOR             VARCHAR(50)	NOT NULL,
  REGISTRATION_YEAR INTEGER     NOT NULL,
  CREDITS           INTEGER     NOT NULL,
  PRIMARY KEY (ID));

CREATE TABLE METADATA.ENROLLMENT (
  ID                INTEGER     NOT NULL AUTO_INCREMENT,
  STUDENT_ID        INTEGER   	NOT NULL,
  COURSE_ID         INTEGER   	NOT NULL,
  SECTION           VARCHAR(2)	NOT NULL,
  ROOM              VARCHAR(8)	NOT NULL,
  SEMESTER          VARCHAR(5)	NOT NULL,
  GRADE             INTEGER     ,
  PRIMARY KEY (ID),
  INDEX ENROL_STUDENT_FK_IX (STUDENT_ID),
  FOREIGN KEY (STUDENT_ID)
    REFERENCES STUDENTS(ID)
    ON DELETE RESTRICT,
  INDEX ENROL_COURSE_FK_IX (COURSE_ID),
  FOREIGN KEY (COURSE_ID)
    REFERENCES COURSES(ID)
    ON DELETE RESTRICT
  );

  CREATE UNIQUE INDEX ENROL_UK_IX1 ON METADATA.ENROLLMENT(STUDENT_ID, COURSE_ID);
