INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(19465539,'Leonard','Cohen','leonard.cohen@techuni.com','Electronics Engineering', 2019, 190);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(20848476,'Leonardo','Dicaprio','leonardo.dicaprio@techuni.com','Electrical Engineering', 2020, 126);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(20866453,'Talulah','Bankhead','talulah.bankhead@techuni.com','Chemical Engineering', 2020, 137);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(21587483,'Deborah','Kerr','deborah.kerr@techuni.com','Environmental Engineering', 2021, 80);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(19657484,'Derek','Jetter','derek.jetter@techuni.com','Aeronautical Engineering', 2019, 188);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(20567827,'Ajay','Singh','ajay.singh@techuni.com','Computer Science', 2020, 122);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(20523362,'Ari','Joukama','ari.joukama@techuni.com','Accounting', 2020, 122);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(18523624,'Marcelo','Tiboni','marcelo.tiboni@techuni.com','Industrial Engineering', 2018, 220);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(20238521,'Fernando','Perez','fernando.perez@techuni.com','Acoustical Engineering', 2020, 127);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(18456234,'Jean-Marc','Lazzari','jean.lazzari@techuni.com','Business', 2018, 227);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(21523854,'Julie','Andrews','julie.andrews@techuni.com','Biomedical Engineering', 2021, 88);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(18647545,'Karim','Benzema','karim.benzema@techuni.com','Sports Engineering', 2018, 243);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(21674945,'Kylian','Mbappe','kylian.mbappe@techuni.com','Sports Engineering', 2021, 65);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(21573883,'Muchen','Wang','muchen.wang@techuni.com','Electrical Engineering', 2021, 75);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(18854675,'Monica','Bellucci','monica.bellucci@techuni.com','Mechanical Engineering', 2018, 223);

INSERT INTO METADATA.STUDENTS
(ID, FIRST_NAME, LAST_NAME, EMAIL, MAJOR, REGISTRATION_YEAR, CREDITS)
VALUES
(20482483,'Himari','Yamaha','himari.yamaha@techuni.com','Computer Science', 2020, 140);
